### ISSUE TITLE
aocc fails with 5 or more mpi rank

### ISSUE THREAD

**Issue by kiranktp** [UK-MAC/TeaLeaf_ref#5]

**Comment by caxwl** [comment]
Apologies for the delay, we had a look at issue using AMD testbed (EPYC 7742) with AOCC 3.1.0
using https://github.com/UK-MAC/TeaLeaf_ref/tree/bugfix/AOCC branch
 `make COMPILER=AOCC IEEE=1`

bm1, bm2, bm3 all passed with 6 MPI ranks, larger bm4/5 passed with 24 MPI ranks. 
Which benchmark caused the issue?

**Comment by douglas-shanks** [comment]
When compiling with aocc/2.x I have seen jobs fail as @kiranktp describes . But when switching to aocc/3.x I have a similar experience to @caxwl in that all of the benchmarks pass. I'm assuming that this was probably an aocc bug in version 2.x which has since been resolved in later versions of the compiler.
